
mod_version=1.9.2

mod_id=absentbydesign
mod_license=MIT
mod_authors=Lothrazar
mod_description=mod
mod_name=Absent by Design
mod_group_id=com.lothrazar.absentbydesign
curse_id=305840
curse_slug=absent-by-design
modrinth_id=absent-by-design

flib_version=0.2.8
flib_file=8482026
