
mod_version=1.9.0

mod_id=absentbydesign
mod_license=MIT
mod_authors=Lothrazar
mod_description=mod
mod_name=Absent by Design
mod_group_id=com.lothrazar.absentbydesign
curse_id=305840

flib_version=1.0.0-SNAPSHOT
